dependencies:
  build:
    - go:1.12.1

build_targets:
  - name: default
    dependencies:
      containers:
        postgres:
          ports:
            - 5440:5440
          label: postgres
          image: postgis/postgis:9.5-2.5
          environment:
            - POSTGRES_USER=loggitest
            - POSTGRES_PASSWORD=loggitest
            - POSTGRES_DB=loggitest
       redis:
         label: redis
         image: redis:latest
         port_check:
           port: 6379
           timeout: 30
    tags:
      os: linux

    commands:
      - go get
      - go build
      - go test ./...

  - name: deploy
    tags:
      os: linux

    commands:
      - go get
      - go build
      - go test ./...
      # yb package ...
ci:
  builds:
    - name: default
      build_target: default
      when: branch is 'master' OR action is 'pull_request'


package:
  docker:
    base_image: alpine
    image: demo-server
    working_dir: /
    exec: /demo-server
  artifacts:
    - demo-server
